apiVersion: apps/v1
kind: Deployment
metadata:
  name: jp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jp
  template:
    metadata:
      labels:
        app: jp
    spec:
      containers:
      - image: okteto.dev/mjkop:latest
        name: jp
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://iq.com"
        - name: Vless_UUID
          value: "f8bfb621-6728-4a6c-ae69-2106cd3d7c8a"
        - name: Vless_Path
          value: "/vl555"
        - name: Vmess_UUID
          value: "f8bfb621-6728-4a6c-ae69-2106cd3d7c8a"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
